// <auto-generated />
namespace DataAccess.Model.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20160912_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20160912_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201609120742042_20160912_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
